version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend  # Diretório onde está o Dockerfile do frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"  # Mapeia a porta 80 do contêiner para a 3001 do host
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"  # Corrigido erro de sintaxe
    environment:
      - DATABASE_URL=postgres://postgres:faculdade@db:5432/chess_db
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: faculdade
      POSTGRES_DB: chess_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
