services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend

    expose:
      - "80"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - DATABASE_URL=postgres://user:faculdade@db:5432/chess_db
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chess_db
    ports:
      - "5432:5432"

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
